import assert from 'node:assert/strict';import fs from 'node:fs';
import {openDatabase} from '../scripts/sqlite-adapter.mjs';import {readCatalog} from '../server/storage.js';import {normalizeOperation,applyOperation,importOperations,listOperations,decideOperation,graphToken} from '../server/operations.js';import worker from '../dist/server/index.js';
const seed=JSON.parse(fs.readFileSync('data/catalog.json')),ev={sourceUrl:'https://example.org/test',sourceType:'Network-free fixture',checkedAt:'2026-10-02',note:'Test-only evidence; never published as catalog data'};
const labels={zh:'测试',en:'Fixture',ja:'テスト'},entity=id=>({kind:'entity',...ev,node:{id,type:'person',labels,description:labels}});
const db=openDatabase();let c=await readCatalog(db,seed);const original=await graphToken(c);
let imported=await importOperations(db,[entity('fixture_person'),entity('fixture_person')],c);assert.equal(imported.inserted,1);assert.equal(imported.skipped,1);assert.equal((await readCatalog(db,seed)).nodes.length,seed.nodes.length);
async function decide(kind,id,decision='approve',database=db){const catalog=await readCatalog(database,seed),state=await listOperations(database,catalog),r=state.operations.find(x=>id?x.id===id:x.operation.kind===kind&&x.status===(decision==='undo'?'approved':'pending'));assert(r);return decideOperation(database,r.id,{decision,expectedVersion:r.version,expectedEpoch:state.epoch,graphToken:state.graphToken,note:'Test decision'},catalog,decision==='undo')}
assert.equal((await decide('entity')).status,200);c=await readCatalog(db,seed);assert(c.nodes.some(n=>n.id==='fixture_person'));let state=await listOperations(db,c),id=state.operations[0].id;assert(state.operations[0].canUndo);assert.equal((await decide(null,id,'undo')).status,200);assert.equal(await graphToken(await readCatalog(db,seed)),original);
assert.equal((await decide('entity')).status,200);c=await readCatalog(db,seed);
const relation={kind:'relationship',...ev,relationship:{source:'fixture_person',target:'song_summer_connection',type:'composer',attributes:{scope:'fixture'}}};await importOperations(db,[relation],c);assert.equal((await decide('relationship')).status,200);c=await readCatalog(db,seed);assert(c.edges.some(e=>e.source==='fixture_person'));
state=await listOperations(db,c);assert(!state.operations.find(r=>r.id===id).canUndo);assert.equal((await decide(null,id,'undo')).status,409);
const rel=state.operations.find(r=>r.operation.kind==='relationship');assert.equal((await decide(null,rel.id,'undo')).status,200);assert.equal((await decide(null,id,'undo')).status,200);
// Source, full-batch validation and references fail closed.
for(const changed of [{...entity('bad'),sourceUrl:'javascript:alert(1)'},{...entity('bad'),checkedAt:'2026-02-30'},{...entity('bad'),sourceType:''},{...entity('bad'),node:{...entity('bad').node,media:[{}]}}])assert.throws(()=>normalizeOperation(changed,c));
const before=db.sqlite.prepare('SELECT count(*) n FROM catalog_operations').get().n;await assert.rejects(()=>importOperations(db,[entity('valid_but_rejected'),{kind:'nonsense',...ev}],c));assert.equal(db.sqlite.prepare('SELECT count(*) n FROM catalog_operations').get().n,before);
assert.throws(()=>applyOperation(c,normalizeOperation({...entity('badref'),node:{...entity('badref').node,editionId:'missing'}},c)));
// Merge keeps source aliases/evidence/link history and redirects all references; reversing is exact.
const mergeDb=openDatabase();let mc=await readCatalog(mergeDb,seed);const from=mc.nodes.find(n=>n.id==='person_taeko_onuki');const clone=structuredClone(from);for(const k of ['media','serviceLinks','schemaVersion','updatedAt','originalJapanese','romanization','scope','unknownCredits','portraitEmbed','coverPhotoEmbed','mediaCoverage'])delete clone[k];clone.id='fixture_taeko_duplicate';const duplicate={kind:'entity',...ev,node:clone};await importOperations(mergeDb,[duplicate],mc);assert.equal((await decide('entity',null,'approve',mergeDb)).status,200);mc=await readCatalog(mergeDb,seed);const prior=await graphToken(mc);const merge={kind:'merge',...ev,fromId:from.id,intoId:clone.id,confirmSameIdentity:true};await importOperations(mergeDb,[merge],mc);assert.equal((await decide('merge',null,'approve',mergeDb)).status,200);mc=await readCatalog(mergeDb,seed);assert(!mc.nodes.some(n=>n.id===from.id));assert.equal(mc.entityAliases[from.id],clone.id);const kept=mc.nodes.find(n=>n.id===clone.id);assert(kept.sources.includes(ev.sourceUrl));assert.deepEqual(kept.media,from.media);assert.deepEqual(kept.serviceLinks,from.serviceLinks);assert.deepEqual(kept.portraitEmbed,from.portraitEmbed);assert.deepEqual(kept.coverPhotoEmbed,from.coverPhotoEmbed);assert.deepEqual(kept.mediaCoverage,from.mediaCoverage);assert(kept.mergedRecords.some(n=>n.id===from.id));assert.equal(mc.nodes.find(n=>n.id==='album_sunshower').artistId,clone.id);assert.equal((await decide('merge',null,'undo',mergeDb)).status,200);assert.equal(await graphToken(await readCatalog(mergeDb,seed)),prior);
// Exact-release matching never spills into another edition or auto-accepts any researched candidate.
const matchDb=openDatabase();const headers={'Content-Type':'application/json',Origin:'https://test.invalid','oai-authenticated-user-id':'fixture','Sec-Fetch-Site':'same-origin'},env={DB:matchDb,SITE_REVIEW_MODE:'owner-private',SITE_REVIEW_ADMIN_USER_IDS:'["fixture"]',SITE_REVIEW_ORIGIN:'https://test.invalid'};
const get=async()=>{const r=await worker.fetch(new Request('https://test.invalid/api/operations',{headers}),env);assert.equal(r.status,200);return r.json()};let queue=await get();assert.equal(queue.operations.length,54);assert(queue.operations.every(r=>r.status==='pending'&&!r.blocked));assert.equal((await readCatalog(matchDb,seed)).nodes.filter(n=>n.type==='track'&&n.recordingId).length,0);
const chosen=queue.operations[0];assert.equal((await decide(null,chosen.id,'approve',matchDb)).status,200);let matched=await readCatalog(matchDb,seed);assert.equal(matched.nodes.find(n=>n.id===chosen.operation.trackId).recordingId,chosen.operation.recordingId);assert.equal(matched.nodes.filter(n=>n.type==='track'&&n.recordingId).length,1);assert.equal((await decide(null,chosen.id,'undo',matchDb)).status,200);assert.equal((await get()).operations.find(r=>r.id===chosen.id).status,'pending');
// Auth, CSRF, malformed/multibyte limits, no-service-credential identity bypass.
const body={operations:[entity('api_fixture')]};const post=async(h=headers,b=body)=>worker.fetch(new Request('https://test.invalid/api/operations/preview',{method:'POST',headers:h,body:JSON.stringify(b)}),env);
for(const h of [{...headers,Origin:'null'},{...headers,'oai-authenticated-user-id':''},{...headers,'Sec-Fetch-Site':'cross-site'},{...headers,'oai-authenticated-user-id':'','OAI-Sites-Authorization':'Bearer fake'}])assert.equal((await post(h)).status,403);
assert.equal((await post({...headers,'Content-Type':'text/plain'})).status,415);assert.equal((await post(headers,{...body,padding:'界'.repeat(23000)})).status,400);assert.equal((await post(headers,{operations:Array(51).fill(body.operations[0])})).status,400);assert.equal((await post()).status,200);
// Durable migration adds tables without changing original approval/candidate history.
const migration=fs.readFileSync('drizzle/0003_numerous_umar.sql','utf8');assert(!/\b(DROP|DELETE|UPDATE|INSERT)\b/i.test(migration));
for(const database of [db,mergeDb,matchDb])database.sqlite.close();console.log('PASS structural intake, merge lineage/reference preservation, exact undo, recording boundaries, queued provenance, auth and migration');
