import fs from 'node:fs';import assert from 'node:assert/strict';
import {openDatabase} from '../scripts/sqlite-adapter.mjs';import {decideCandidate} from '../server/review.js';import {readCatalog} from '../server/storage.js';import worker from '../dist/server/index.js';
const DB=openDatabase(),seed=JSON.parse(fs.readFileSync('data/catalog.json'));
const env={DB,SITE_REVIEW_MODE:'owner-private',SITE_REVIEW_ORIGIN:'https://test.invalid'};
const headers={'Content-Type':'application/json',Origin:'https://test.invalid','oai-authenticated-user-id':'fixture-owner','Sec-Fetch-Site':'same-origin'};
async function call(path,body,h=headers,e=env){const r=await worker.fetch(new Request('https://test.invalid'+path,{method:body?'POST':'GET',headers:h,...(body?{body:JSON.stringify(body)}:{})}),e);return {status:r.status,body:await r.json()}}
assert.equal((await call('/api/review')).status,200);
assert.equal((await call('/api/review/import',{candidates:[]},{...headers,'oai-authenticated-user-id':''})).status,403);
assert.equal((await call('/api/review/import',{candidates:[]},{...headers,Origin:'https://evil.invalid'})).status,403);
assert.equal((await call('/api/review/import',{candidates:[]},{...headers,Origin:'null'})).status,403);
assert.equal((await call('/api/review/import',{candidates:[]},{...headers,'Content-Type':'text/plain'})).status,415);
assert.equal((await call('/api/review/import',{candidates:[]},headers,{...env,SITE_REVIEW_MODE:'disabled'})).status,403);
const sample={entityId:'album_sunshower',field:'catalogNumber',value:'TEST-123',sourceUrl:'https://example.org/fixture',checkedAt:'2026-10-02',note:'Network-free fixture only'};
assert.equal((await call('/api/review/import',{candidates:[{...sample,sourceUrl:'javascript:alert(1)'}]})).status,400);
const imported=await call('/api/review/import',{candidates:[sample]});assert.equal(imported.status,200);const id=imported.body.ids[0];
assert.equal((await call('/api/review/import',{candidates:[sample]})).body.ids[0],id);
assert.equal((await call('/api/review/'+id,{decision:'approve',expectedVersion:99})).status,409);
assert.equal((await call('/api/review/'+id,{decision:'reject',expectedVersion:1})).status,400);
assert.equal((await call('/api/review/'+id,{decision:'approve',expectedVersion:1})).status,200);
assert((await call('/api/review/'+id,{decision:'approve',expectedVersion:1})).body.repeated);
assert.equal((await call('/api/graph')).body.nodes.find(n=>n.id===sample.entityId).attributes.catalogNumber.value,'TEST-123');
const next=structuredClone(seed);next.revision='review-persistence-test';const updated=await readCatalog(DB,next);assert.equal(updated.nodes.find(n=>n.id===sample.entityId).attributes.catalogNumber.value,'TEST-123');
assert.equal(DB.sqlite.prepare('SELECT count(*) as n FROM review_events WHERE candidate_id=?').get(id).n,1);
const choices=[{...sample,field:'label',value:'fixture-A'},{...sample,field:'label',value:'fixture-B'}];const ids=(await call('/api/review/import',{candidates:choices})).body.ids;
const outcomes=await Promise.all(ids.map(x=>call('/api/review/'+x,{decision:'approve',expectedVersion:1})));assert.deepEqual(outcomes.map(x=>x.status).sort(),[200,409]);
assert.equal((await call('/api/review/candidate_'+'0'.repeat(64),{decision:'approve',expectedVersion:1})).status,404);
const rejected=(await call('/api/review/import',{candidates:[{...sample,field:'label',value:'fixture-reject'}]})).body.ids[0];assert.equal((await call('/api/review/'+rejected,{decision:'reject',expectedVersion:1,note:'Fixture rejected'})).status,200);
assert.equal((await call('/api/review/import',{candidates:[],large:'x'.repeat(66000)})).status,400);
const orphan=(await call('/api/review/import',{candidates:[{...sample,value:'ORPHAN-TEST'}]})).body.ids[0];const orphanCatalog=structuredClone(seed);orphanCatalog.nodes=orphanCatalog.nodes.filter(n=>n.id!==sample.entityId);assert.equal((await decideCandidate(DB,orphan,{decision:'reject',expectedVersion:1,note:'Entity removed'},orphanCatalog)).status,200);
assert.equal((await call('/api/review/import',{candidates:[{...sample,field:'releaseDate',value:'2026-99-99'}]})).status,400);
DB.sqlite.close();console.log('PASS review auth, CSRF, validation, idempotency, atomic decisions, concurrency and overlay persistence');
