import assert from 'node:assert/strict';
import fs from 'node:fs';
import {openDatabase} from '../scripts/sqlite-adapter.mjs';
import {readPublicCatalog} from '../server/public-catalog.js';
import {importCandidates,decideCandidate} from '../server/review.js';
const seed=JSON.parse(fs.readFileSync('data/catalog.json'));
const DB=openDatabase();
let batches=0;const batch=DB.batch.bind(DB);DB.batch=async(...args)=>{batches++;return batch(...args)};
const a=await readPublicCatalog(DB,seed),afterFirst=batches,b=await readPublicCatalog(DB,seed);
assert.equal(a,b);assert.equal(batches,afterFirst,'Warm cache checks epoch without re-reading snapshot tables');
const payload={entityId:'album_sunshower',field:'catalogNumber',value:'SEO-CACHE-TEST',sourceUrl:'https://example.org/cache',checkedAt:'2026-10-06'};
await importCandidates(DB,[payload],a);
const row=DB.sqlite.prepare('SELECT id,version FROM candidates').get();
const approved=await decideCandidate(DB,row.id,{decision:'approve',expectedVersion:row.version,note:'Synthetic cache verification'},a);
assert.equal(approved.status,200);
const corrected=await readPublicCatalog(DB,seed);assert.notEqual(corrected,a);assert.equal(corrected.nodes.find(n=>n.id===payload.entityId).attributes.catalogNumber?.value,payload.value);
const next=structuredClone(seed);next.revision=seed.revision+'-seo-fixture';next.nodes.find(n=>n.id===payload.entityId).description.en='Synthetic source update';
const upgraded=await readPublicCatalog(DB,next);assert.equal(upgraded.revision,next.revision);assert.equal(upgraded.nodes.find(n=>n.id===payload.entityId).description.en,'Synthetic source update');assert.equal(upgraded.nodes.find(n=>n.id===payload.entityId).attributes.catalogNumber?.value,payload.value);
const other=openDatabase();const independent=await readPublicCatalog(other,seed);assert.notEqual(independent,upgraded);assert.notEqual(independent.nodes.find(n=>n.id===payload.entityId).attributes.catalogNumber?.value,payload.value);
DB.sqlite.close();other.sqlite.close();console.log('PASS SEO catalog cache: database isolation, one epoch read on warm requests, immediate approval invalidation, source revision and preserved overrides');
