import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
import {serveSEO,publicOrigin,isPublicSEO,sitemapEntries,PAGE_SIZE} from '../server/seo.js';
const catalog=JSON.parse(fs.readFileSync('data/catalog.json')),articles=JSON.parse(fs.readFileSync('public/articles.json')),about=JSON.parse(fs.readFileSync('public/about.json'));
const context={catalog,articles,about},R=globalThis.CityPopRoutes,origin='https://city-pop.softmatrix.io',env={PUBLIC_ORIGIN:origin,SEO_INDEXABLE:true};
const request=(path,options={})=>new Request(origin+path,options);
const get=(path,overrides={},ctx=context)=>serveSEO(request(path),{...env,...overrides},ctx);
const dom=html=>new JSDOM(html).window.document;
assert.equal(publicOrigin(env),origin);assert.equal(publicOrigin({...env,PUBLIC_ORIGIN:origin+'/'}),origin);
for(const value of [undefined,'','http://city-pop.softmatrix.io','https://localhost','https://localhost:443','https://127.0.0.1','https://[::1]','https://10.0.0.1','https://example.chatgpt.site','https://user:pass@city-pop.softmatrix.io','https://city-pop.softmatrix.io/path','https://city-pop.softmatrix.io/?x=1','https://city-pop.softmatrix.io/#x','https://city-pop.softmatrix.io:8443',' https://city-pop.softmatrix.io','https://city-pop.softmatrix.io.'])assert.equal(publicOrigin({PUBLIC_ORIGIN:value}),null,String(value));
assert.equal(isPublicSEO(request('/en/'),env),true);assert.equal(isPublicSEO(new Request('https://attacker.example/en/'),env),false);assert.equal(isPublicSEO(request('/en/'),{...env,SEO_INDEXABLE:'true'}),false);
assert.equal(await get('/api/graph'),null);assert.equal(await get('/'),null);assert.equal(await get('/favicon.svg'),null);
const n=catalog.nodes.find(n=>n.id==='person_tatsuro_yamashita'),path=R.pathFor(n),article=articles.find(a=>a.entityId===n.id);
let response=await get(path);assert.equal(response.status,200);assert.match(response.headers.get('x-robots-tag'),/^index,/);
let html=await response.text(),document=dom(html);
assert.equal(document.querySelector('html').lang,'en');assert.equal(document.querySelector('h1').textContent,n.labels.en);assert.equal(document.querySelector('link[rel=canonical]').href,origin+path);
assert.equal(document.querySelectorAll('link[rel=alternate][hreflang]').length,4);
assert.equal(document.querySelector('link[hreflang="zh-CN"]').href,origin+R.pathFor(n,'zh'));
for(const p of article.locales.en.paragraphs)assert(html.includes(p.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')),'All essay paragraphs are server-rendered');
assert(html.includes('Current catalog facts'));assert(html.includes('Sources and evidence'));assert(html.includes('Related entries and credits'));
let graph=JSON.parse(document.querySelector('script[type="application/ld+json"]').textContent)['@graph'];
assert(graph.some(x=>x['@type']==='Person'));assert(graph.some(x=>x['@type']==='BreadcrumbList'));assert(!graph.some(x=>x.aggregateRating||x.review||x.datePublished));assert(!graph.find(x=>x['@type']==='Article').dateModified);assert(!graph.find(x=>x['@type']==='WebPage').dateModified);
assert(document.querySelector('body[data-clarity-mask=true]'));assert(document.querySelector('#privacy-settings'));assert(html.indexOf('src="/routes.js"')<html.indexOf('src="/analytics.js"'));assert(!html.includes('src="/app.js"'));
for(const lang of ['zh','ja']){const res=await get(R.pathFor(n,lang));const doc=dom(await res.text());assert.equal(doc.documentElement.lang,{zh:'zh-CN',ja:'ja'}[lang]);assert.equal(doc.querySelector('h1').textContent,n.labels[lang]);assert(doc.querySelector('.essay-body').textContent.includes(article.locales[lang].paragraphs[0]));}
const contextual=catalog.nodes.find(n=>n.type==='track');response=await get(R.pathFor(contextual));html=await response.text();document=dom(html);assert.match(response.headers.get('x-robots-tag'),/^noindex, follow$/);assert.equal(document.querySelector('link[rel=canonical]').href,origin+R.pathFor(contextual));assert.equal(JSON.parse(document.querySelector('script[type="application/ld+json"]').textContent)['@graph'].find(x=>x.identifier===contextual.id)['@type'],'ListItem');
for(const [type,expected]of [['album','MusicAlbum'],['song','CreativeWork'],['edition','MusicRelease'],['work','MusicComposition'],['recording','MusicRecording'],['person','Person']]){const node=catalog.nodes.find(n=>n.type===type),doc=dom(await(await get(R.pathFor(node))).text());assert.equal(JSON.parse(doc.querySelector('script[type="application/ld+json"]').textContent)['@graph'].find(x=>x.identifier===node.id)['@type'],expected);}
const group=catalog.nodes.find(n=>n.id==='person_sugar_babe');document=dom(await(await get(R.pathFor(group))).text());assert(JSON.parse(document.querySelector('script[type="application/ld+json"]').textContent)['@graph'].some(x=>x['@type']==='MusicGroup'));
for(const q of ['?utm_source=x','?q=secret','?view=review','?x=%3Cscript%3E']){response=await get(path+q);html=await response.text();document=dom(html);assert.equal(response.status,200);assert.match(response.headers.get('x-robots-tag'),/^noindex/);assert.equal(document.querySelector('link[rel=canonical]').href,origin+path);assert(!document.head.textContent.includes('secret'));}
for(const p of ['/en/missing','/en/artists/no-such-entity','/en/browse/labels','/en/browse/albums/page/999','/en/browse/albums/page/999/','/en/artists/%2Ftest'])assert.equal((await get(p)).status,404,p);
for(const [from,to]of [['/en','/en/'],[path+'/',path],['/en/albums/album-timely-2008',R.pathFor(catalog.nodes.find(n=>n.id==='edition_timely_2008_flcf4243'))]]){response=await get(from);assert.equal(response.status,308);assert.equal(response.headers.get('location'),to);}
response=await get('/en/browse/tracks/page/2');document=dom(await response.text());assert.equal(document.querySelectorAll('.entries>li').length,PAGE_SIZE);assert(document.querySelector('a[rel=prev]'));assert(document.querySelector('a[rel=next]'));
response=await get('/en/about');html=await response.text();document=dom(html);assert(document.querySelector('.essay-body').textContent.includes(about.locales.en.paragraphs[0]));assert.equal(document.querySelectorAll('figure').length,3);assert(html.includes('2006'));assert(html.includes('CC BY-SA'));
for(const p of ['/en/',path,'/en/about','/en/browse','/en/missing','/en','/robots.txt','/sitemap.xml']){const head=await serveSEO(request(p,{method:'HEAD'}),env,context),normal=await get(p);assert.equal(head.status,normal.status);assert.equal(await head.text(),'');}
assert.equal((await serveSEO(request(path,{method:'POST'}),env,context)).status,405);
for(const overrides of [{PUBLIC_ORIGIN:''},{SEO_INDEXABLE:false},{SEO_INDEXABLE:'true'}]){response=await get(path,overrides);html=await response.text();assert.match(response.headers.get('x-robots-tag'),/^noindex/);assert(!html.includes('rel="canonical"'));assert.match(await(await get('/robots.txt',overrides)).text(),/Disallow: \/\n/);assert.equal((await get('/sitemap.xml',overrides)).status,404);}
const poisoned=await serveSEO(new Request('https://evil.example'+path,{headers:{Host:'city-pop.softmatrix.io','X-Forwarded-Host':'city-pop.softmatrix.io','X-Forwarded-Proto':'https'}}),env,context);assert.match(poisoned.headers.get('x-robots-tag'),/^noindex/);assert(!(await poisoned.text()).includes('rel="canonical"'));
const entries=sitemapEntries(context);assert.equal(new Set(entries.map(e=>e.path)).size,entries.length);assert(entries.every(e=>!e.path.includes('?')&&!/^\/(en|zh|ja)\/tracks\//.test(e.path)));assert.equal(entries.filter(e=>e.path===path)[0].lastmod,null);assert.equal(entries.find(e=>e.path==='/en/').lastmod,null);assert.equal(entries.find(e=>e.path==='/en/browse').lastmod,null);assert.equal(entries.filter(e=>e.path==='/en/about')[0].lastmod,about.updatedAt);
const xml=await(await get('/sitemap.xml')).text();assert(xml.includes('<loc>'+origin+path+'</loc>'));assert(!xml.includes('album-timely-2008'));assert(!xml.includes('<changefreq>'));assert.equal((await get('/sitemap.xml?x=1')).status,404);
const changed=structuredClone(context),edited=changed.catalog.nodes.find(x=>x.id===n.id);edited.labels.en='Renamed </title><script>alert(1)</script>';edited.description.en='A </script><script>alert(2)</script> description';edited.attributes.test={value:'<img src=x onerror=alert(3)>',sourceUrl:'javascript:alert(4)',reviewStatus:'approved',checkedAt:'2026-10-05'};edited.updatedAt='2026-10-05';changed.articles.find(x=>x.entityId===n.id).locales.en.paragraphs[0]='A </script><script>alert(5)</script> essay';
response=await get(path,{},changed);html=await response.text();document=dom(html);assert.equal(document.querySelectorAll('script').length,4);assert(!document.querySelector('img[onerror]'));assert(!document.querySelector('a[href^="javascript:"]'));assert(document.querySelector('h1').textContent.includes('</title>'));assert(document.querySelector('.notice'));assert(document.querySelector('#facts').textContent.includes('<img src=x onerror=alert(3)>'));graph=JSON.parse(document.querySelector('script[type="application/ld+json"]').textContent)['@graph'];assert.equal(graph.find(x=>x.identifier===n.id).name,edited.labels.en);
console.log(`PASS multilingual SSR, complete essays, semantic JSON-LD, current facts, noindex/canonical separation, safe origins, HEAD/404/XSS and ${entries.length} sitemap URLs`);

const translatedPages=[];for(const locale of ['en','zh','ja']){const page=dom(await(await get('/'+locale+'/browse/artists/page/2')).text());translatedPages.push([...page.querySelectorAll('.entries a')].map(a=>new URL(a.href,origin).pathname.replace(/^\/(en|zh|ja)/,'')));}assert.deepEqual(translatedPages[0],translatedPages[1]);assert.deepEqual(translatedPages[0],translatedPages[2]);console.log('PASS translated pagination preserves identical entity membership across all locale alternates');
