import fs from 'node:fs';
import assert from 'node:assert/strict';
import {snapshotJSONChunks,SNAPSHOT_JSON_LIMIT} from '../server/snapshot-json.js';
import {seedCatalog,readCatalog} from '../server/storage.js';
import {openDatabase} from '../scripts/sqlite-adapter.mjs';
const bytes=x=>new TextEncoder().encode(x).length;
const rows=Array.from({length:12},(_,i)=>({i,text:'🎷都市「声」"\\\n'}));
const small=snapshotJSONChunks(rows,80);assert(small.length>1);assert(small.every(x=>bytes(x)<=80));assert.deepEqual(small.flatMap(x=>JSON.parse(x)),rows);
assert.deepEqual(snapshotJSONChunks([]),[]);
const boundary=[{text:'界🎷'}],exact=bytes(JSON.stringify(boundary));assert.deepEqual(snapshotJSONChunks(boundary,exact),[JSON.stringify(boundary)]);assert.throws(()=>snapshotJSONChunks(boundary,exact-1),/row exceeds/);
assert.throws(()=>snapshotJSONChunks([undefined]),/Invalid snapshot row/);assert.throws(()=>snapshotJSONChunks([],SNAPSHOT_JSON_LIMIT+1),/Invalid snapshot chunk limit/);
assert.throws(()=>snapshotJSONChunks([{text:'界'.repeat(600000)}]),/row exceeds/);
const seed=JSON.parse(fs.readFileSync('data/catalog.json')),db=openDatabase();
const realBatch=db.batch.bind(db);let imported=[];
db.batch=async statements=>{if(statements.some(s=>s.sql.startsWith('DELETE FROM entities')))imported.push(statements);for(const s of statements)for(const arg of s.args||[])if(typeof arg==='string')assert(bytes(arg)<=SNAPSHOT_JSON_LIMIT,'Every parameter remains below the existing safe bound');return realBatch(statements)};
const first=await readCatalog(db,seed);assert.equal(imported.length,1);assert(imported[0].filter(s=>s.sql.startsWith('INSERT INTO entities')).length>=2,'This real expanded snapshot crosses the old parameter threshold');assert(imported[0].length<=32);
const onceEpoch=db.sqlite.prepare("SELECT epoch FROM catalog_state WHERE id='graph'").get().epoch;await readCatalog(db,seed);assert.equal(imported.length,1,'Same revision does not import again');assert.equal(db.sqlite.prepare("SELECT epoch FROM catalog_state WHERE id='graph'").get().epoch,onceEpoch);
const before=JSON.stringify(first),bad=structuredClone(seed);bad.revision='duplicate-in-later-json-chunk';bad.nodes.push(structuredClone(seed.nodes[0]));
await assert.rejects(()=>seedCatalog(db,bad),/UNIQUE/);assert.equal(imported.length,2);assert(imported[1].filter(s=>s.sql.startsWith('INSERT INTO entities')).length>=2);
assert.equal(JSON.stringify(await readCatalog(db,seed)),before,'Failure in a later insert rolls back deletes and all earlier chunks');assert.equal(db.sqlite.prepare("SELECT epoch FROM catalog_state WHERE id='graph'").get().epoch,onceEpoch,'Failed transaction does not advance epoch');assert.equal(db.sqlite.prepare('SELECT id FROM imports ORDER BY rowid DESC LIMIT 1').get().id,seed.revision);
const tooBig=structuredClone(seed);tooBig.revision='oversized-single-row';tooBig.nodes[0].extra='界'.repeat(600000);const batchCount=imported.length;await assert.rejects(()=>seedCatalog(db,tooBig),/row exceeds/);assert.equal(imported.length,batchCount,'Oversized row is rejected before any replacement batch');assert.equal(JSON.stringify(await readCatalog(db,seed)),before);
db.sqlite.close();console.log(`PASS UTF-8 byte-exact snapshot chunks; ${seed.nodes.length} real entities imported atomically below 1.8 MB per parameter; idempotency, later-chunk rollback and oversized-row rejection`);
