const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert'),vm=require('vm');
const data=JSON.parse(fs.readFileSync('data/catalog.json'));
const dom=new JSDOM(fs.readFileSync('public/index.html','utf8'),{url:'https://citypop.test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,d=w.document;w.DATA=data;w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({measureText:t=>({width:t.length*7})},{get:(o,k)=>o[k]||(()=>{})});w.requestAnimationFrame=()=>1;w.cancelAnimationFrame=()=>{};w.scrollTo=()=>{};
// Media-title assertions below intentionally compare the Chinese catalog labels.
w.localStorage.setItem('citypop-language','zh');
vm.runInContext(fs.readFileSync('public/app.js','utf8'),dom.getInternalVMContext());
const run=x=>vm.runInContext(x,dom.getInternalVMContext());
for(const n of data.nodes.filter(n=>['album','song'].includes(n.type))){run(`select(${JSON.stringify(n.id)})`);const f=d.querySelector('#detail iframe');const playable=run(`!!playableLink(index.get(${JSON.stringify(n.id)}))`);assert.equal(!!f,playable,n.id);if(f){assert(f.title.includes(n.labels.zh));assert.equal(f.loading||f.getAttribute('loading'),'lazy');assert(!f.getAttribute('allow').includes('autoplay'));assert(/https:\/\/(open.spotify.com\/embed\/(album|track)\/|www.youtube-nocookie.com\/embed\/)/.test(f.src));assert(!f.src.includes('autoplay=1'));assert(d.querySelector('.album-player a[target="_blank"]'))}else assert(d.querySelector('#detail .media-pending'),n.id)}
const invalid={type:'song',serviceLinks:[{service:'spotify',resourceType:'artist',status:'verified',url:'https://open.spotify.com/artist/1234567890123456789012'},{service:'youtube',status:'verified',url:'https://youtube.com/results?search_query=x'}]};assert.equal(run(`playableLink(${JSON.stringify(invalid)})`),undefined);
assert.equal(run(`serviceURL({service:'spotify',resourceType:'track',url:'https://open.spotify.com/artist/1234567890123456789012'})`),null);assert.equal(run(`serviceURL({service:'spotify',resourceType:'track',url:'https://user:pass@open.spotify.com/track/1234567890123456789012'})`),null);
for(const n of data.nodes.filter(n=>n.portraitEmbed||n.coverPhotoEmbed)){run(`select(${JSON.stringify(n.id)})`);const licensed=run(`!!portrait(index.get(${JSON.stringify(n.id)}))`),f=d.querySelector('#detail .provider-portrait iframe');if(licensed){assert(d.querySelector('#detail .portrait img'),n.id+' licensed portrait takes precedence');assert(!f,n.id+' avoid duplicate portrait widget')}else{assert(f,n.id);assert(f.src.includes('/embed/artist/'));assert(!f.getAttribute('allow').includes('autoplay'));if(n.coverPhotoEmbed&&!n.portraitEmbed)assert(d.querySelector('#detail .media-pending'))}d.querySelector('#index-toggle').click();assert.equal(d.querySelectorAll('#detail iframe').length,0);d.querySelector('#index-toggle').click();assert(d.querySelector(licensed?'#detail .portrait img':'#detail .provider-portrait iframe'))}
for(const lang of ['zh','en','ja']){d.querySelector(`[data-lang="${lang}"]`).click();d.querySelector('#nav [data-view="guide"]').click();assert.equal(d.querySelectorAll('.media-checklist li').length,128);assert(d.querySelector('.coverage-counts').textContent.includes('/ 39'));assert(d.querySelector('.coverage-counts').textContent.includes('/ 4'))}
dom.window.close();console.log('PASS every album/song embed, safe provider IDs, nonautoplay, fallback and all 128 coverage entries');
