// Audited structural proposals. Nothing is applied before an explicit decision.
const types=['artist','person','album','song','edition','recording','work','track','label'];
const relations=['arranger','co_produced','composer','corresponds_to','edition_of','lyricist','member_of','performer','produced','recording_entry_for','released','represents_work','track_on','recording_of'];
const referenceFields=['albumId','artistId','editionId','compositionEntryId','recordingId','legacyEntryId'];
const clone=v=>JSON.parse(JSON.stringify(v));
export const canonical=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
const equal=(a,b)=>canonical(a)===canonical(b);
const text=(v,n=1000)=>typeof v==='string'&&v.trim().length>0&&v.length<=n;
const identifier=v=>typeof v==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9_.:-]{0,149}$/.test(v)&&!['constructor','prototype','__proto__'].includes(v);
const uuid=v=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(v);
const url=v=>{try{const u=new URL(v);return text(v,2000)&&u.protocol==='https:'&&!u.username&&!u.password}catch{return false}};
const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const langs=v=>object(v)&&['zh','en','ja'].every(k=>text(v[k],1000));
export async function hash(v){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof v==='string'?v:canonical(v))))).map(n=>n.toString(16).padStart(2,'0')).join('')}
export const graphToken=c=>hash({revision:c.revision,nodes:c.nodes,edges:c.edges,entityAliases:c.entityAliases});
function evidence(c){if(!url(c.sourceUrl)||!date(c.checkedAt)||!text(c.sourceType,60)||!text(c.note,1000))throw Error('evidence_required');return {sourceUrl:c.sourceUrl,sourceType:c.sourceType,checkedAt:c.checkedAt,note:c.note}}
function strings(v,n=30){return Array.isArray(v)&&v.length<=n&&v.every(x=>text(x,1000))}
function safeKeys(v){if(!object(v))return false;return Object.keys(v).every(k=>/^[a-zA-Z][a-zA-Z0-9]{0,63}$/.test(k)&&!['constructor','prototype'].includes(k))}
function entity(n,e,catalog){
 if(!object(n)||!identifier(n.id)||!types.includes(n.type)||!langs(n.labels)||!langs(n.description))throw Error('invalid_entity');
 const allowed=['id','type','labels','description','sources','aliases','attributes','externalIds','year',...referenceFields,'position','slotLabel'];
 if(Object.keys(n).some(k=>!allowed.includes(k)))throw Error('unsupported_entity_field');
 if(n.year!==undefined&&(!Number.isInteger(n.year)||n.year<1||n.year>9999))throw Error('invalid_year');
 if(n.sources!==undefined&&(!Array.isArray(n.sources)||n.sources.length>30||!n.sources.every(url)))throw Error('invalid_sources');
 if(n.aliases!==undefined&&!strings(n.aliases))throw Error('invalid_aliases');
 if(n.externalIds!==undefined&&(!safeKeys(n.externalIds)||Object.entries(n.externalIds).some(([k,v])=>!text(v,150)||k.startsWith('musicbrainz')&&!uuid(v))))throw Error('invalid_external_ids');
 const attrs=n.attributes||{};if(!safeKeys(attrs)||Object.keys(attrs).length>30)throw Error('invalid_attributes');
 for(const [k,v]of Object.entries(attrs)){const def=catalog.properties.find(p=>p.key===k);if(!def||!object(v)||!url(v.sourceUrl)||!date(v.checkedAt)||!('value'in v))throw Error('invalid_attribute_evidence');const x=v.value;if(!(typeof x==='string'&&x.length<=1000||typeof x==='number'&&Number.isFinite(x)||typeof x==='boolean'||strings(x)))throw Error('invalid_attribute');if(def.valueType==='number'&&typeof x!=='number'||def.valueType==='list'&&!Array.isArray(x)||['string','date'].includes(def.valueType)&&typeof x!=='string')throw Error('attribute_type_mismatch');if(def.valueType==='date'&&(!/^\d{4}(?:-\d{2}(?:-\d{2})?)?$/.test(x)||!date(x.length===4?x+'-01-01':x.length===7?x+'-01':x)))throw Error('invalid_date');if(['trackNumber','trackCount','albumNumber','birthYear','durationMs','discCount','vinylWeightGrams'].includes(k)&&(!Number.isInteger(x)||x<(k==='durationMs'?0:1)))throw Error('invalid_number')}
 const node={...clone(n),sources:[...new Set([...(n.sources||[]),e.sourceUrl])],aliases:n.aliases||[],attributes:attrs,externalIds:n.externalIds||{},media:[],serviceLinks:[],schemaVersion:3,updatedAt:e.checkedAt};
 for(const key of referenceFields)if(node[key]!=null&&!identifier(node[key]))throw Error('invalid_reference');
 return node;
}
function checkReferences(n,c){const by=new Map(c.nodes.map(n=>[n.id,n]));const want=(key,type,required=false)=>{if(n[key]==null){if(required)throw Error('missing_'+key)}else if(by.get(n[key])?.type!==type)throw Error('invalid_'+key)};
 if(n.type==='edition'){want('albumId','album',true);if(!text(n.attributes.catalogNumber?.value)||!text(n.attributes.releaseDate?.value))throw Error('edition_identity_required')}
 if(n.type==='track'){if(n.recordingId)throw Error('use_recording_match');want('editionId','edition',true);want('compositionEntryId','song');want('recordingId','recording');if(!Number.isInteger(n.position)||n.position<1||!text(n.slotLabel,60)||!text(n.attributes.trackTitle?.value))throw Error('track_identity_required');if(n.attributes.trackNumber?.value!==n.position||n.attributes.slotLabel?.value!==n.slotLabel)throw Error('track_position_mismatch');if(c.nodes.some(x=>x.id!==n.id&&x.type==='track'&&x.editionId===n.editionId&&(x.position===n.position||x.slotLabel===n.slotLabel)))throw Error('track_slot_exists')}
 if(n.legacyEntryId)want('legacyEntryId','song');
 const allowedRefs={albumId:['edition'],editionId:['track'],compositionEntryId:['track'],recordingId:['track'],legacyEntryId:['work','recording'],artistId:['album','edition','recording','song','work']};for(const key of referenceFields)if(n[key]!=null&&!allowedRefs[key].includes(n.type))throw Error('unexpected_reference');if(n.artistId&&!['artist','person'].includes(by.get(n.artistId)?.type))throw Error('invalid_artistId');
}
const normalized=s=>s.normalize('NFKC').toLowerCase().replace(/[\s\p{P}\p{S}]/gu,'');
export function suggestions(n,c){return c.nodes.filter(x=>x.type===n.type&&x.id!==n.id).map(x=>{const shared=Object.keys(n.externalIds||{}).filter(k=>n.externalIds[k]===x.externalIds?.[k]);const names=[...Object.values(n.labels||{}),...(n.aliases||[])].map(normalized);const overlap=[...Object.values(x.labels||{}),...(x.aliases||[])].some(s=>names.includes(normalized(s)));return {id:x.id,labels:x.labels,reason:shared.length?'same_external_id':overlap?'same_normalized_name':null,externalIdKeys:shared}}).filter(x=>x.reason).slice(0,10)}
function checkRelationship(r,c){const a=c.nodes.find(n=>n.id===r.source),b=c.nodes.find(n=>n.id===r.target);if(!a||!b||a===b)throw Error('relationship_endpoint_missing');const rules={edition_of:[['edition'],['album']],track_on:[['track','song'],['edition','album']],corresponds_to:[['track'],['song']],represents_work:[['song'],['work']],recording_entry_for:[['recording'],['song']],recording_of:[['recording'],['work']],member_of:[['artist','person'],['artist']]};const rule=rules[r.type];if(rule&&(!rule[0].includes(a.type)||!rule[1].includes(b.type)))throw Error('relationship_type_mismatch');if(['arranger','composer','lyricist','performer','produced','co_produced','released'].includes(r.type)&&!['artist','person'].includes(a.type))throw Error('credit_source_type');if(['arranger','composer','lyricist','performer','produced','co_produced','released'].includes(r.type)&&!['album','song','work','recording','edition','track'].includes(b.type))throw Error('credit_target_type');if(r.type==='track_on'&&a.type==='song'&&b.type!=='album')throw Error('relationship_type_mismatch');if(r.type==='edition_of'&&a.albumId!==b.id||r.type==='track_on'&&a.type==='track'&&a.editionId!==b.id||r.type==='corresponds_to'&&a.compositionEntryId!=null&&a.compositionEntryId!==b.id)throw Error('relationship_identity_conflict')}
export function normalizeOperation(raw,c){if(!object(raw))throw Error('invalid_operation');const e=evidence(raw);let o={kind:raw.kind,...e};
 if(raw.kind==='entity')o.node=entity(raw.node,e,c);
 else if(raw.kind==='relationship'){if(!object(raw.relationship)||!identifier(raw.relationship.source)||!identifier(raw.relationship.target)||!relations.includes(raw.relationship.type))throw Error('invalid_relationship');const r=raw.relationship;if(r.attributes!==undefined&&(!safeKeys(r.attributes)||Object.values(r.attributes).some(v=>!text(v,1000))))throw Error('invalid_relationship_attributes');o.relationship={source:r.source,target:r.target,type:r.type,attributes:r.attributes||{}}}
 else if(raw.kind==='recording_match'){for(const k of ['trackId','editionId','recordingId']){if(!identifier(raw[k]))throw Error('invalid_match');o[k]=raw[k]}if(!uuid(raw.releaseId))throw Error('release_identity_required');o.releaseId=raw.releaseId;if(!text(raw.matchBasis,1000))throw Error('match_basis_required');o.matchBasis=raw.matchBasis}
 else if(raw.kind==='merge'){if(!identifier(raw.fromId)||!identifier(raw.intoId)||raw.fromId===raw.intoId)throw Error('invalid_merge');o.fromId=raw.fromId;o.intoId=raw.intoId;if(raw.confirmSameIdentity!==true)throw Error('identity_confirmation_required');o.confirmSameIdentity=true}
 else throw Error('invalid_operation_kind');return o;
}
function union(a=[],b=[]){const map=new Map([...a,...b].map(x=>[canonical(x),x]));return [...map.values()]}
function applyMerge(c,o){const from=c.nodes.find(n=>n.id===o.fromId),into=c.nodes.find(n=>n.id===o.intoId);if(!from||!into||from.type!==into.type)throw Error('merge_identity_mismatch');
 // Never silently choose between conflicting facts, editions or recordings.
 for(const key of ['year',...referenceFields,'position','slotLabel'])if(from[key]!=null&&into[key]!=null&&!equal(from[key],into[key]))throw Error('merge_conflicting_'+key);
 for(const group of ['attributes','externalIds'])for(const k of Object.keys(from[group]||{}))if(into[group]?.[k]!==undefined&&!equal(group==='attributes'?from[group][k].value:from[group][k],group==='attributes'?into[group][k].value:into[group][k]))throw Error('merge_conflicting_'+group);
 if(['edition','track','recording','work'].includes(from.type)&&!Object.keys(from.externalIds||{}).some(k=>from.externalIds[k]===into.externalIds?.[k]))throw Error('merge_external_identity_required');
 const merged={...from,...into,attributes:{...from.attributes,...into.attributes},externalIds:{...from.externalIds,...into.externalIds},sources:union(union(from.sources,into.sources),[o.sourceUrl]),aliases:union(union(from.aliases,into.aliases),Object.values(from.labels)),media:union(from.media,into.media),serviceLinks:union(from.serviceLinks,into.serviceLinks)};
 // Retain complete origin records, including each conflicting description/label/provenance.
 merged.mergedRecords=union(union(into.mergedRecords||[],from.mergedRecords||[]),[{...from,mergedRecords:undefined}]);
 c.nodes=c.nodes.filter(n=>n.id!==from.id).map(n=>n.id===into.id?merged:n);
 for(const n of c.nodes)for(const key of referenceFields)if(n[key]===from.id)n[key]=into.id;
 const grouped=new Map();for(const edge of c.edges){const r={...edge,source:edge.source===from.id?into.id:edge.source,target:edge.target===from.id?into.id:edge.target};if(r.source===r.target)throw Error('merge_self_relationship');const key=canonical([r.source,r.target,r.type,r.attributes||{}]);if(grouped.has(key)){const old=grouped.get(key);old.sources=union(old.sources,r.sources);old.mergedRelationships=union(old.mergedRelationships||[],[r])}else grouped.set(key,r)}c.edges=[...grouped.values()];
 for(const [k,v]of Object.entries(c.entityAliases||{}))if(v===from.id)c.entityAliases[k]=into.id;c.entityAliases={...c.entityAliases,[from.id]:into.id};
}
export function applyOperation(catalog,o){const c=clone(catalog);const by=id=>c.nodes.find(n=>n.id===id);
 if(o.kind==='entity'){if(by(o.node.id)||c.entityAliases?.[o.node.id])throw Error('entity_exists');checkReferences(o.node,c);c.nodes.push(clone(o.node));const n=o.node;const refs=n.type==='edition'?[['edition_of',n.albumId]]:n.type==='track'?[['track_on',n.editionId],...(n.compositionEntryId?[['corresponds_to',n.compositionEntryId]]:[])]:[];for(const [type,target]of refs)c.edges.push({id:'operation_'+n.id+'_'+type,source:n.id,target,type,sources:[o.sourceUrl],status:'sourced',checkedAt:o.checkedAt,attributes:{}})}
 if(o.kind==='relationship'){checkRelationship(o.relationship,c);if(o.relationship.type==='corresponds_to')by(o.relationship.source).compositionEntryId=o.relationship.target;if(c.edges.some(e=>e.source===o.relationship.source&&e.target===o.relationship.target&&e.type===o.relationship.type&&equal(e.attributes||{},o.relationship.attributes)))throw Error('relationship_exists');c.edges.push({...o.relationship,id:'operation_'+encodeURIComponent(canonical(o.relationship)),sources:[o.sourceUrl],status:'sourced',checkedAt:o.checkedAt})}
 if(o.kind==='recording_match'){const t=by(o.trackId),ed=by(o.editionId),r=by(o.recordingId);if(t?.type!=='track'||ed?.type!=='edition'||r?.type!=='recording'||t.editionId!==ed.id||ed.externalIds?.musicbrainzRelease!==o.releaseId||!uuid(r.externalIds?.musicbrainzRecording))throw Error('match_identity_mismatch');if(t.recordingId)throw Error('track_already_matched');const source=new URL(o.sourceUrl);if(source.hostname!=='musicbrainz.org'||!['/release/'+o.releaseId,'/recording/'+r.externalIds.musicbrainzRecording].includes(source.pathname.replace(/\/$/,'')))throw Error('match_source_identity_mismatch');t.recordingId=r.id;t.sources=union(t.sources,[o.sourceUrl]);t.attributes.identityStatus={value:'exact_release_track_link_reviewed_physical_master_unverified',sourceUrl:o.sourceUrl,sourceType:o.sourceType,checkedAt:o.checkedAt};t.attributes.recordingIdentity={value:r.externalIds.musicbrainzRecording,sourceUrl:o.sourceUrl,sourceType:o.sourceType,checkedAt:o.checkedAt,matchBasis:o.matchBasis,reviewStatus:'approved'};c.edges.push({id:'match_'+t.id,source:t.id,target:r.id,type:'records_recording',sources:[o.sourceUrl],status:'sourced',checkedAt:o.checkedAt,attributes:{releaseId:o.releaseId,matchBasis:o.matchBasis}})}
 if(o.kind==='merge'){applyMerge(c,o);const slots=new Set(),positions=new Set();for(const n of c.nodes.filter(n=>n.type==='track')){const slot=canonical([n.editionId,n.slotLabel]),pos=canonical([n.editionId,n.position]);if(slots.has(slot)||positions.has(pos))throw Error('merge_duplicate_track_slot');slots.add(slot);positions.add(pos)}}return c;
}
export function applyOperations(c,rows,overrides=[]){const conflicts=[];for(const row of rows){try{const o=JSON.parse(row.payload);c=applyOperation(c,o);if(o.kind==='entity'){const n=c.nodes.find(n=>n.id===o.node.id);for(const r of overrides.filter(r=>r.entity_id===n.id)){n.attributes[r.field]=JSON.parse(r.payload);n.sources=union(n.sources,[n.attributes[r.field].sourceUrl]);n.updatedAt=r.updated_at.slice(0,10);if(r.field==='releaseDate'&&['album','edition'].includes(n.type))n.year=Number(String(n.attributes[r.field].value).slice(0,4))}}}catch(e){conflicts.push({id:row.id,error:e.message})}}c.operationConflicts=conflicts;return c}
const identity=o=>{const {checkedAt,note,...claim}=o;if(claim.node){claim.node={...claim.node};delete claim.node.updatedAt}return canonical(claim)};
export async function previewOperations(db,input,c){if(!Array.isArray(input)||!input.length||input.length>50)throw Error('operation_limit');const existing=(await db.prepare('SELECT id,status FROM catalog_operations').all()).results;const seen=new Set(),rows=[];for(let i=0;i<input.length;i++){try{const operation=normalizeOperation(input[i],c),id='operation_'+await hash(identity(operation));const prior=existing.find(x=>x.id===id);let error=null;try{applyOperation(c,operation)}catch(e){error=e.message}const disposition=seen.has(id)?'duplicate_batch':prior?'existing':error?'blocked':'new';seen.add(id);rows.push({row:i+1,id,operation,disposition,error,existingStatus:prior?.status,suggestions:operation.kind==='entity'?suggestions(operation.node,c):[],impact:operation.kind==='merge'?{references:c.nodes.filter(n=>referenceFields.some(k=>n[k]===operation.fromId)).length,relationships:c.edges.filter(e=>e.source===operation.fromId||e.target===operation.fromId).length}:null})}catch(e){rows.push({row:i+1,disposition:'invalid',error:e.message})}}
 return {rows,valid:!rows.some(r=>r.disposition==='invalid'),graphToken:await graphToken(c),epoch:c.epoch,counts:Object.fromEntries(['new','existing','duplicate_batch','blocked','invalid'].map(k=>[k,rows.filter(r=>r.disposition===k).length]))};
}
export async function importOperations(db,input,c){const p=await previewOperations(db,input,c);if(!p.valid)throw Error('invalid_batch');const now=new Date().toISOString(),rows=p.rows.filter(r=>['new','blocked'].includes(r.disposition)).map(r=>({id:r.id,kind:r.operation.kind,payload:JSON.stringify(r.operation)}));let inserted=0;if(rows.length){const results=await db.batch([db.prepare("INSERT OR IGNORE INTO catalog_operations(id,kind,payload,status,version,created_at,updated_at) SELECT json_extract(value,'$.id'),json_extract(value,'$.kind'),json_extract(value,'$.payload'),'pending',1,?,? FROM json_each(?)").bind(now,now,JSON.stringify(rows))]);inserted=results[0].meta?.changes??results[0].changes}return {inserted,skipped:input.length-inserted}};
export async function listOperations(db,c){const rows=(await db.prepare('SELECT * FROM catalog_operations ORDER BY created_at DESC,id').all()).results;const token=await graphToken(c);const latest=rows.filter(r=>r.status==='approved').sort((a,b)=>b.applied_order-a.applied_order)[0];return {graphToken:token,epoch:c.epoch,conflicts:c.operationConflicts||[],operations:rows.map(r=>{const operation=JSON.parse(r.payload);let blocked=null;if(r.status==='pending')try{applyOperation(c,operation)}catch(e){blocked=e.message}return {id:r.id,operation,status:r.status,version:r.version,blocked,suggestions:operation.kind==='entity'?suggestions(operation.node,c):[],canUndo:(r.id===latest?.id&&r.after_token===token)||(c.operationConflicts||[]).some(x=>x.id===r.id),createdAt:r.created_at}}),events:(await db.prepare('SELECT * FROM operation_events ORDER BY rowid DESC LIMIT 100').all()).results}};
export async function decideOperation(db,id,body,c,undo=false){const row=await db.prepare('SELECT * FROM catalog_operations WHERE id=?').bind(id).first();if(!row)return {status:404,error:'operation_not_found'};if(!body||!Number.isInteger(body.expectedVersion)||!Number.isInteger(body.expectedEpoch)||!text(body.note,500)||!text(body.graphToken,64))return {status:400,error:'decision_context_required'};
 const action=undo?'undo':body.decision;if(!['approve','reject','undo'].includes(action))return {status:400,error:'invalid_decision'};if(row.version!==body.expectedVersion||row.status!==(undo?'approved':'pending')||body.expectedEpoch!==c.epoch||body.graphToken!==await graphToken(c))return {status:409,error:'review_conflict'};
 let after=null;if(action==='approve'){if(c.operationConflicts?.length)return {status:409,error:'resolve_operation_conflicts'};try{after=await graphToken(applyOperation(c,JSON.parse(row.payload)))}catch(e){return {status:409,error:e.message}}}if(undo){const latest=await db.prepare("SELECT id FROM catalog_operations WHERE status='approved' ORDER BY applied_order DESC LIMIT 1").first();if(!(c.operationConflicts||[]).some(x=>x.id===id)&&(latest?.id!==id||row.after_token!==body.graphToken))return {status:409,error:'undo_conflict'}}
 const event=crypto.randomUUID(),now=new Date().toISOString(),status=action==='approve'?'approved':action==='reject'?'rejected':'pending';await db.batch([
 db.prepare('UPDATE catalog_operations SET status=?,version=version+1,decision_id=?,applied_order=?,after_token=?,updated_at=? WHERE id=? AND version=? AND status=? AND EXISTS(SELECT 1 FROM catalog_state WHERE id=\'graph\' AND epoch=?) AND (SELECT id FROM imports ORDER BY rowid DESC LIMIT 1)=?').bind(status,event,action==='approve'?c.epoch+1:null,after,now,id,row.version,row.status,c.epoch,c.revision),
 db.prepare("UPDATE catalog_state SET epoch=epoch+1 WHERE id='graph' AND EXISTS(SELECT 1 FROM catalog_operations WHERE id=? AND decision_id=?)").bind(id,event),
 db.prepare('INSERT INTO operation_events(id,operation_id,action,note,created_at) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM catalog_operations WHERE id=? AND decision_id=?)').bind(event,id,action,body.note.trim(),now,id,event)
 ]);const result=await db.prepare('SELECT decision_id,version,status FROM catalog_operations WHERE id=?').bind(id).first();return result.decision_id===event?{status:200,result:{id,version:result.version,status:result.status}}:{status:409,error:'review_conflict'};
}
