import {createRequire}from'node:module';import fs from'node:fs';import vm from'node:vm';import assert from'node:assert/strict';import worker from '../../dist/server/index.js';
const root=new URL('../../',import.meta.url).pathname.replace(/\/$/,'');process.chdir(root);const require=createRequire(root+'/package.json'),{JSDOM}=require('jsdom'),{openDatabase}=await import(root+'/scripts/sqlite-adapter.mjs'),DB=openDatabase();
const dom=new JSDOM(fs.readFileSync('public/index.html','utf8'),{url:'https://citypop.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document;
w.DATA=JSON.parse(fs.readFileSync('data/catalog.json'));w.TextEncoder=TextEncoder;w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({measureText:t=>({width:t.length*7})},{get:(o,k)=>o[k]||(()=>{})});w.HTMLCanvasElement.prototype.getBoundingClientRect=()=>({width:1000,height:700,left:0,top:0});w.matchMedia=()=>({matches:false});w.scrollTo=()=>{};w.requestAnimationFrame=()=>1;w.cancelAnimationFrame=()=>{};
let inflight=0;const calls=[];w.fetch=async(path,options={})=>{calls.push([path,options.method||'GET']);const headers=new Headers(options.headers||{});headers.set('Origin','https://citypop.test');headers.set('oai-authenticated-user-id','fixture');headers.set('Sec-Fetch-Site','same-origin');inflight++;try{return await worker.fetch(new Request(new URL(path,'https://citypop.test'),{...options,headers}),{DB,SITE_REVIEW_MODE:'owner-private',SITE_REVIEW_ADMIN_USER_IDS:'["fixture"]',SITE_REVIEW_ORIGIN:'https://citypop.test'})}finally{inflight--}};
vm.runInContext(fs.readFileSync('public/app.js','utf8'),dom.getInternalVMContext());
const flush=async()=>{let stable=0;for(let i=0;i<500;i++){await new Promise(r=>setTimeout(r,10));if(inflight===0&&!w.eval('reviewLoading||reviewBusy||opLoading||opBusy')){if(++stable===3)return}else stable=0}throw Error('UI did not settle within 5s')};const input=(key,value)=>{const el=d.querySelector(`[data-op-input="${key}"]`);assert(el,key);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));el.dispatchEvent(new w.Event('change',{bubbles:true}))};
d.querySelector('[data-view="review"]').click();await flush();assert(d.querySelector('#operation-draft-preview'));
for(const lang of ['en','ja','zh']){d.querySelector(`[data-lang="${lang}"]`).click();assert(d.querySelector('#operations h2').textContent.trim());assert(!d.querySelector('#operations').textContent.includes('undefined'))}
input('id','audit_dom_person');input('type','person');for(const lang of ['zh','en','ja']){input('labels_'+lang,'Audit <img src=x onerror=alert(1)>');input('description_'+lang,'Safe <script>alert(1)</script>')};input('sourceUrl','https://example.org/dom');input('sourceType','Fixture');input('checkedAt','2026-10-02');input('note','Independent DOM↔Worker fixture');
d.querySelector('#operation-draft-preview').click();await flush();assert(d.querySelector('.operation-preview'));assert.equal(d.querySelectorAll('#operations img,#operations script').length,0);assert.equal(DB.sqlite.prepare("SELECT count(*) n FROM catalog_operations WHERE payload LIKE '%audit_dom_person%'").get().n,0);
d.querySelector('#operation-preview-cancel').click();assert(!d.querySelector('.operation-preview'));assert.equal(d.querySelector('[data-op-input="id"]').value,'audit_dom_person');d.querySelector('#operation-draft-preview').click();await flush();d.querySelector('#operation-enqueue').click();await flush();const row=DB.sqlite.prepare("SELECT * FROM catalog_operations WHERE payload LIKE '%audit_dom_person%'").get();assert.equal(row.status,'pending');assert(!w.eval("index.has('audit_dom_person')"));
d.querySelector(`[data-operation="${row.id}"][data-operation-action="approve"]`).click();d.querySelector('#operation-confirm').click();await flush();assert.equal(DB.sqlite.prepare('SELECT status FROM catalog_operations WHERE id=?').get(row.id).status,'pending');const reason=d.querySelector('#operation-reason');reason.value='Confirm sourced test entity';reason.dispatchEvent(new w.Event('input'));d.querySelector('#operation-confirm').click();await flush();assert.equal(DB.sqlite.prepare('SELECT status FROM catalog_operations WHERE id=?').get(row.id).status,'approved');assert(w.eval("index.has('audit_dom_person')"));
const filter=d.querySelector('#operation-filter');filter.value='approved';filter.dispatchEvent(new w.Event('change'));const undo=d.querySelector(`[data-operation="${row.id}"][data-operation-action="undo"]`);assert(undo);undo.click();d.querySelector('#operation-decision-cancel').click();assert.equal(DB.sqlite.prepare('SELECT status FROM catalog_operations WHERE id=?').get(row.id).status,'approved');d.querySelector(`[data-operation="${row.id}"][data-operation-action="undo"]`).click();const undoReason=d.querySelector('#operation-reason');undoReason.value='Remove test entity';undoReason.dispatchEvent(new w.Event('input'));d.querySelector('#operation-confirm').click();await flush();assert.equal(DB.sqlite.prepare('SELECT status FROM catalog_operations WHERE id=?').get(row.id).status,'pending');assert(!w.eval("index.has('audit_dom_person')"));
assert.equal(DB.sqlite.prepare('SELECT count(*) n FROM operation_events WHERE operation_id=?').get(row.id).n,2);w.close();DB.sqlite.close();console.log('PASS independent DOM↔Worker E2E: three languages, escaped content, create form, preview/cancel, queue, required reason, approve, refreshed graph, undo/cancel, restored graph and audit events ('+calls.length+' API calls)');
